# Generated by Django 4.0.6 on 2022-07-18 14:33

import battlefront.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('attack_factor', models.FloatField(default=1.0, help_text='attack multiplier', validators=[battlefront.validators.validate_factor])),
                ('attack_modifier', models.IntegerField(default=3, help_text='attack adder', validators=[battlefront.validators.validate_attack_mod])),
                ('endurance_factor', models.FloatField(default=1.0, help_text='endurance multiplier', validators=[battlefront.validators.validate_factor])),
                ('endurance_modifier', models.IntegerField(default=6, help_text='endurance adder', validators=[battlefront.validators.validate_endurance_mod])),
                ('life_factor', models.FloatField(default=0.0, help_text='life multiplier', validators=[battlefront.validators.validate_factor])),
                ('life_modifier', models.IntegerField(default=0, help_text='life adder', validators=[battlefront.validators.validate_life_mod])),
                ('defense_factor', models.FloatField(default=1.0, help_text='defense multiplier', validators=[battlefront.validators.validate_factor])),
                ('defense_modifier', models.IntegerField(default=3, help_text='defense adder', validators=[battlefront.validators.validate_defense_mod])),
            ],
        ),
    ]
