# Generated by Django 4.0.6 on 2022-07-19 08:28

import battlefront.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefront', '0004_alter_weapon_life_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='attack_factor',
            field=models.FloatField(default=1.0, help_text='attack multiplier, between 0.5 and 1.5', validators=[battlefront.validators.validate_factor]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='attack_modifier',
            field=models.IntegerField(default=3, help_text='attack adder, between 0 and 6', validators=[battlefront.validators.validate_attack_mod]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='defense_factor',
            field=models.FloatField(default=1.0, help_text='defense multiplier, between 0.5 and 1.5', validators=[battlefront.validators.validate_factor]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='defense_modifier',
            field=models.IntegerField(default=0, help_text='defense adder, between -3 and 3', validators=[battlefront.validators.validate_defense_mod]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='endurance_factor',
            field=models.FloatField(default=1.0, help_text='endurance multiplier, between 0.5 and 1.5', validators=[battlefront.validators.validate_factor]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='endurance_modifier',
            field=models.IntegerField(default=6, help_text='endurance adder, between 3 and 9', validators=[battlefront.validators.validate_endurance_mod]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='life_factor',
            field=models.FloatField(default=0.5, help_text='life multiplier, between 0.0 and 1.0', validators=[battlefront.validators.validate_life_factor]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='life_modifier',
            field=models.IntegerField(default=0, help_text='life adder, between -3 and 3', validators=[battlefront.validators.validate_life_mod]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='target_type',
            field=models.CharField(choices=[('H', 'Heal Single Target'), ('A', 'Attack Single Target'), ('G', 'Attack Group'), ('D', 'Defend Single Target'), ('W', 'Defend Group')], help_text="one of 'H', 'A', 'G', 'D', 'W', see source code", max_length=1),
        ),
    ]
