# Generated by Django 4.0.6 on 2022-07-19 09:05

import battlefront.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battlefront', '0005_alter_weapon_attack_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('attack_capacity', models.IntegerField(default=6, help_text='attack characteristic, between 0 and 12', validators=[battlefront.validators.validate_factor])),
                ('endurance_capacity', models.IntegerField(default=6, help_text='endurance multiplier, between 0 and 12', validators=[battlefront.validators.validate_factor])),
                ('life_capactity', models.IntegerField(default=18, help_text='life multiplier, between 12 and 24', validators=[battlefront.validators.validate_life_factor])),
                ('defense_capacity', models.IntegerField(default=3, help_text='defense multiplier, between 0 and 6', validators=[battlefront.validators.validate_factor])),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='battlefront.group')),
                ('group_target', models.ManyToManyField(blank=True, null=True, related_name='group_target', to='battlefront.group', verbose_name='attacked group target')),
                ('single_target', models.ManyToManyField(blank=True, null=True, to='battlefront.fighter', verbose_name='attacked single target')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battlefront.weapon')),
            ],
        ),
    ]
