# Generated by Django 4.0.6 on 2022-07-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefront', '0006_group_fighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='group_target',
            field=models.ManyToManyField(blank=True, related_name='group_target', to='battlefront.group', verbose_name='attacked group target'),
        ),
    ]
