# Generated by Django 4.0.6 on 2022-07-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefront', '0007_alter_fighter_group_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='single_target',
            field=models.ManyToManyField(blank=True, to='battlefront.fighter', verbose_name='attacked single target'),
        ),
    ]
