# Generated by Django 4.0.6 on 2022-07-19 09:57

import battlefront.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battlefront', '0008_alter_fighter_single_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='attack_capacity',
            field=models.IntegerField(default=6, help_text='attack characteristic, between 0 and 12', validators=[battlefront.validators.validate_attack_capacity]),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='defense_capacity',
            field=models.IntegerField(default=3, help_text='defense multiplier, between 0 and 6', validators=[battlefront.validators.validate_defense_capacity]),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='endurance_capacity',
            field=models.IntegerField(default=6, help_text='endurance multiplier, between 0 and 12', validators=[battlefront.validators.validate_endurance_capacity]),
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='group_target',
        ),
        migrations.AddField(
            model_name='fighter',
            name='group_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_target', to='battlefront.group', verbose_name='attacked group target'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='life_capactity',
            field=models.IntegerField(default=18, help_text='life multiplier, between 12 and 24', validators=[battlefront.validators.validate_life_capacity]),
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='single_target',
        ),
        migrations.AddField(
            model_name='fighter',
            name='single_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='battlefront.fighter', verbose_name='attacked single target'),
        ),
    ]
